title: "RSQKit: Research Software Quality Kit"
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: "RSQKit: Research Software Quality Kit"
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

topnav_banner: "The current version of RSQKit is a work in progress. Any content should not be considered final at this stage."

description: "The Research Software Quality Kit is a resource to help researchers that code, Research Software Engineers, and anyone in between learn about and apply best practices in creating research software and code."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme


sass:
  style: compressed
  sourcemap: never

exclude:
  - README.md
  - Gemfile

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  -
    scope:
      path: "pages/your_tasks/"
    values:
      type: your_tasks
      type_img: /assets/img/section-icons/tick.svg
  -
    scope:
      path: "pages/your_tasks/TEMPLATE_your_tasks.md"
      type: "pages"
    values:
        sitemap: false
        search_exclude: true
        no_robots: true
  -
    scope:
      path: "pages/contributing"
      type: "pages"
    values:
      layout: "page"
      sidebar: contributing

theme_variables:
  topnav:
    brand_logo: assets/img/everse_logo.png
    twitter: https://twitter.com/eosc_everse

plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-scholar