title: "RSQKit: Research Software Quality Kit"
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: "The Research Software Quality Kit is a resource to help researchers that code, Research Software Engineers, and anyone in between learn about and apply best practices in creating research software and code."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme


sass:
  style: compressed
  sourcemap: never

matomo: https://matomo.research.software/
# Matomo domain where Matomo is running
matomo_id: 7
matomo_cookies: false

exclude:
  - README.md
  - Gemfile

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: main
  -
    scope:
      path: "pages/your_tasks/"
    values:
      type: your_tasks
      type_img: /assets/img/font-awesome-free/list-check-solid.svg
      page_citation: true
  -
    scope:
      path: "pages/your_tasks/TEMPLATE_your_tasks.md"
      type: "pages"
    values:
        sitemap: false
        search_exclude: true
        no_robots: true
  -
    scope:
      path: "pages/research_communities/"
    values:
      type: research_community
      type_img: /assets/img/font-awesome-free/people-group-solid.svg
  -
    scope:
      path: "pages/contributing/"
      type: "pages"
    values:
      layout: "page"
      sidebar: contributing

theme_variables:
  topnav:
    bluesky: https://bsky.app/profile/eosc-everse.bsky.social
    linkedin: https://www.linkedin.com/company/eosc-everse
    fonts:
      - https://fonts.googleapis.com/css?family=Roboto&display=swap
      - https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600;700;800&display=swap


plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-scholar
